services:
  - type: web
    name: instrutores-sistema
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: DISCORD_WEBHOOK_NEW_BOOKING_URL
        sync: false
      - key: DISCORD_WEBHOOK_APPROVED_BOOKING_URL
        sync: false
      - key: DISCORD_WEBHOOK_RESULTS_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: instrutores-db
          property: connectionString

databases:
  - name: instrutores-db
    plan: free
