name: Reverter ultimo commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  revert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Reverter commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git revert --no-edit 3dfbac0
          git push origin main
